# Generated by Django 2.1.7 on 2019-03-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190324_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='subtitle',
            field=models.CharField(max_length=50),
        ),
    ]
