# Generated by Django 2.1.7 on 2019-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190324_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='avatar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='species',
            name='subtitle',
            field=models.CharField(max_length=60),
        ),
    ]
