# Generated by Django 2.1.7 on 2019-03-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190325_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='series', to='api.Species'),
        ),
    ]
