# Generated by Django 2.1.7 on 2019-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190325_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imgURL',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/4/4c/Paramecia_tetraurelia.jpeg', max_length=200),
            preserve_default=False,
        ),
    ]
