# Generated by Django 2.1.7 on 2019-03-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='description',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedbacks',
            old_name='user',
            new_name='yourname',
        ),
    ]
