# Generated by Django 2.1.7 on 2019-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_auto_20190327_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(default='Public', max_length=50),
        ),
    ]
